shell = "/opt/homebrew/bin/fish"

[window.padding]
x = 8
y = 8

[cursor.style]
shape = "Beam"
blinking = "On"

[cursor.vi_mode_style]
shape = "Block"

[font]
normal = { family = "Moralerspace Argon NF" }
size = 13

[hints]
alphabet = "aoeuidhtns"

[[hints.enabled]]
# default. see `man 5 alacritty` > HINTS > enabled
command = "open"
hyperlinks = true
post_processing = true
persist = false
mouse.enabled = true
binding  = { key = "U", mods = "Control|Shift" }
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"

[[hints.enabled]]
regex = "[^ ]+\\.(go|json|jsonnet|libsonnet|md|pl|rb|rs|sh|tf|toml|txt|ya?ml)(:\\d+)?(:\\d+)?"
command = { program = "/opt/homebrew/bin/code", args = ["--goto"] }
binding = { key = "C", mods = "Control|Shift" }
mouse.enabled = true

[[keyboard.bindings]]
key = "T"
mods = "Control"
action = "ToggleViMode"

[[keyboard.bindings]]
key = "Q"
mode = "Vi"
action = "ToggleViMode"
