shell = "/opt/homebrew/bin/fish"

[window.padding]
x = 8
y = 8

[cursor.style]
shape = "Beam"
blinking = "On"

[cursor.vi_mode_style]
shape = "Block"

[font]
normal = { family = "Moralerspace Argon NF" }
size = 13

[hints]
alphabet = "aoeuidhtns"

[[hints.enabled]]
regex = "[^ ]+\\.[-0-9a-z]+(:\\d+)?(:\\d+)?[ $\"]"
command = { program = "/opt/homebrew/bin/code", args = [ "--goto" ] }
binding = { key = "C", mods = "Control|Shift" }
mouse.enabled = true

[[keyboard.bindings]]
key = "T"
mods = "Control"
action = "ToggleViMode"

[[keyboard.bindings]]
key = "Escape"
mode = "Vi"
action = "ToggleViMode"
